# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Flower.create(en:"Achira",scientific_name:"Canna edulis",toxic:false)
Flower.create(en:"Acorn Squash",scientific_name:"Cucurbita pepo",toxic:false)
Flower.create(en:"African Daisy",scientific_name:"Gerbera jamesonii",toxic:false)
Flower.create(en:"African Violet",scientific_name:"Saintpaulia spp.",toxic:false)
Flower.create(en:"Algaroba",scientific_name:"Prosopis limensis",toxic:false)
Flower.create(en:"Aluminum Plant",scientific_name:"Pilea cadieri",toxic:false)
Flower.create(en:"Alumroot",scientific_name:"Heuchera sanguinea",toxic:false)
Flower.create(en:"Alyssum",scientific_name:"Alyssum spp.",toxic:false)
Flower.create(en:"American Rubber Plant",scientific_name:"Peperomia obtusifolia",toxic:false)
Flower.create(en:"Amur Maple",scientific_name:"Acer ginnala",toxic:false)
Flower.create(en:"Anthericum Comosum",scientific_name:"Chlorophytum comosum",toxic:false)
Flower.create(en:"Antirrhinum Multiflorum",scientific_name:"Antirrhinum multiflorum",toxic:false)
Flower.create(en:"Arabian Gentian",scientific_name:"Exacum affine",toxic:false)
Flower.create(en:"Areca Palm",scientific_name:"Dypsis lutescens",toxic:false)
Flower.create(en:"Aregelia",scientific_name:"Neoregalia spp.",toxic:false)
Flower.create(en:"Artillery Plant",scientific_name:"Pilea microphylla",toxic:false)
Flower.create(en:"Asparagus Fern",scientific_name:"Asparagus densiflorus cv sprengeri",toxic:false)
Flower.create(en:"Aspidium falcatum",scientific_name:"Cyrtomium falcatum",toxic:false)
Flower.create(en:"Australian Pine",scientific_name:"Araucaria heterophylla",toxic:false)
Flower.create(en:"Autumn Olive",scientific_name:"Eleagnus spp.",toxic:false)
Flower.create(en:"Baby Rubber Plant",scientific_name:"Peperomia obtusifolia",toxic:false)
Flower.create(en:"Baby’s Breath",scientific_name:"Gypsophila elegans",toxic:false)
Flower.create(en:"Baby’s Tears",scientific_name:"Hypoestes phyllostachya",toxic:false)
Flower.create(en:"Bachelors Buttons",scientific_name:"Centaurea cyanus",toxic:false)
Flower.create(en:"Ball Fern",scientific_name:"Davallia spp.",toxic:false)
Flower.create(en:"Bamboo",scientific_name:"Phyllostachys aurea",toxic:false)
Flower.create(en:"Bamboo Palm",scientific_name:"Chamaedorea elegans",toxic:false)
Flower.create(en:"Bamboo Vine",scientific_name:"Smilax laurifolia",toxic:false)
Flower.create(en:"Banana",scientific_name:"Musa acuminata",toxic:false)
Flower.create(en:"Banana Squash",scientific_name:"Cucurbita maxima var. banana",toxic:false)
Flower.create(en:"Barberton Daisy",scientific_name:"Gerbera jamesonii",toxic:false)
Flower.create(en:"Barnaby's Thistle",scientific_name:"Centaurea solstitialis",toxic:false)
Flower.create(en:"Basil",scientific_name:"Ocimum basilicum",toxic:false)
Flower.create(en:"Beets",scientific_name:"Beta vulgaris",toxic:false)
Flower.create(en:"Begonia, Climbing",scientific_name:"Cissus dicolor",toxic:false)
Flower.create(en:"Begonia, Trailing",scientific_name:"Pellionia daveauana",toxic:false)
Flower.create(en:"Belmore Sentry Palm",scientific_name:"Howea belmoreana",toxic:false)
Flower.create(en:"Big Shagbark Hickory",scientific_name:"Carya laciniosa",toxic:false)
Flower.create(en:"Big Shellbark Hickory",scientific_name:"Carya laciniosa",toxic:false)
Flower.create(en:"Bitter Pecan",scientific_name:"Carya aquatica",toxic:false)
Flower.create(en:"Bitternut",scientific_name:"Carya cordiformis",toxic:false)
Flower.create(en:"Black Haw",scientific_name:"Viburnum lentago",toxic:false)
Flower.create(en:"Black Hawthorn",scientific_name:"Crataegus douglasii",toxic:false)
Flower.create(en:"Black Walnut",scientific_name:"Juglans nigra",toxic:false)
Flower.create(en:"Blackjack Pine",scientific_name:"Pinus ponderosa",toxic:false)
Flower.create(en:"Blaspheme Vine",scientific_name:"Smilax laurifolia",toxic:false)
Flower.create(en:"Bloodleaf",scientific_name:"Iresine herbstii",toxic:false)
Flower.create(en:"Blooming Sally",scientific_name:"Epilobium angustifolium",toxic:false)
Flower.create(en:"Blue Bead",scientific_name:"Clintonia borealis",toxic:false)
Flower.create(en:"Blue Daisy",scientific_name:"Felicia amelloides",toxic:false)
Flower.create(en:"Blue Echeveria",scientific_name:"Echeveria glauca",toxic:false)
Flower.create(en:"Blue Eyed Daisy",scientific_name:"Arctotis stoechadifolia",toxic:false)
Flower.create(en:"Blue-dicks",scientific_name:"Dichelostemma pulchellum",toxic:false)
Flower.create(en:"Blue-dicks 2",scientific_name:"Hookera pulchella",toxic:false)
Flower.create(en:"Blue-dicks 3",scientific_name:"Brodiaea pulchella",toxic:false)
Flower.create(en:"Blue-eyed African Daisy",scientific_name:"Arctotis stoechadifolia",toxic:false)
Flower.create(en:"Bluebottle",scientific_name:"Centaurea cyanus",toxic:false)
Flower.create(en:"Blunt Leaf Peperomia",scientific_name:"Peperomia obtusifolia",toxic:false)
Flower.create(en:"Blushing Bromeliad",scientific_name:"Neoregalia spp.",toxic:false)
Flower.create(en:"Bold Sword Fern",scientific_name:"Nephrolepis biserrata",toxic:false)
Flower.create(en:"Boston Fern",scientific_name:"Nephrolepis exalta bostoniensis",toxic:false)
Flower.create(en:"Bottle Palm",scientific_name:"Beaucarnea recurvata",toxic:false)
Flower.create(en:"Bottle Palm 2",scientific_name:"Nolina tuberculata",toxic:false)
Flower.create(en:"Bottlebrush",scientific_name:"Callistemon species",toxic:false)
Flower.create(en:"Brazilian Orchid",scientific_name:"Sophronitis spp.",toxic:false)
Flower.create(en:"Bride's Bonnet",scientific_name:"Clintonia uniflora",toxic:false)
Flower.create(en:"Bristly Greenbrier",scientific_name:"Smilax hispida",toxic:false)
Flower.create(en:"Brodiaea Pulchella",scientific_name:"Dichelostemma pulchellum",toxic:false)
Flower.create(en:"Broom Hickory",scientific_name:"Carya laciniosa",toxic:false)
Flower.create(en:"Bullbrier",scientific_name:"Smilax rotundifolia",toxic:false)
Flower.create(en:"Bur Gourd",scientific_name:"Cucumis anguria",toxic:false)
Flower.create(en:"Burro's Tail",scientific_name:"Sedum morganianum",toxic:false)
Flower.create(en:"Buttercup Squash",scientific_name:"Cucurbita maxima cv buttercup",toxic:false)
Flower.create(en:"Butterfly Ginger",scientific_name:"Hedychium coronarium",toxic:false)
Flower.create(en:"Butternut Squash",scientific_name:"Cucurbita maxima cv butternut",toxic:false)
Flower.create(en:"Buzzy Lizzie",scientific_name:"Impatiens spp.",toxic:false)
Flower.create(en:"Caeroba",scientific_name:"Calathea insignis",toxic:false)
Flower.create(en:"Calathea",scientific_name:"Calathea spp.",toxic:false)
Flower.create(en:"Calathea Lancifolia 2",scientific_name:"Maranta insignis",toxic:false)
Flower.create(en:"Calathea Lancifolia 3",scientific_name:"Calathea insignis",toxic:false)
Flower.create(en:"California Pitcher Plant",scientific_name:"Darlingtonia californica",toxic:false)
Flower.create(en:"Callistemon Brachyandrus",scientific_name:"Callistemon species",toxic:false)
Flower.create(en:"Callistemon citrinus",scientific_name:"Callistemon citrinus",toxic:false)
Flower.create(en:"Callistemon viminalis",scientific_name:"Callistemon viminalis",toxic:false)
Flower.create(en:"Calochortus nuttalli",scientific_name:"Calochortus spp.",toxic:false)
Flower.create(en:"Camellia",scientific_name:"Camellia japonica",toxic:false)
Flower.create(en:"Canada Hemlock",scientific_name:"Tsuga canadensis",toxic:false)
Flower.create(en:"Canary Date Palm",scientific_name:"Phoenix canariensis",toxic:false)
Flower.create(en:"Candle Plant",scientific_name:"Plectranthus coleoides",toxic:false)
Flower.create(en:"Candycorn Plant",scientific_name:"Hypocyrta nummularia",toxic:false)
Flower.create(en:"Cane Palm",scientific_name:"Dypsis lutescens, chrysalidocarpus lutescens (alternate scientific name)",toxic:false)
Flower.create(en:"Canna Lily",scientific_name:"Canna generalis",toxic:false)
Flower.create(en:"Canterbury-bell",scientific_name:"Gloxinia perennis",toxic:false)
Flower.create(en:"Cape Marigold",scientific_name:"Dimorphotheca pluvialis",toxic:false)
Flower.create(en:"Cape Primrose",scientific_name:"Streptocarpus spp.",toxic:false)
Flower.create(en:"Carob",scientific_name:"Ceratonia siliqua",toxic:false)
Flower.create(en:"Caroba",scientific_name:"Jacaranda procera",toxic:false)
Flower.create(en:"Carolina Hemlock",scientific_name:"Tsuga caroliniana",toxic:false)
Flower.create(en:"Carrion Flower",scientific_name:"Smilax herbacea",toxic:false)
Flower.create(en:"Carrion Flower 2",scientific_name:"Stapelia hirsata",toxic:false)
Flower.create(en:"Carrot Fern",scientific_name:"Onychium japonica",toxic:false)
Flower.create(en:"Carrot Flower",scientific_name:"Daucus carota var. sativa",toxic:false)
Flower.create(en:"Casaba Melon",scientific_name:"Cucumis melo",toxic:false)
Flower.create(en:"Cast Iron Plant",scientific_name:"Aspidistra elatior",toxic:false)
Flower.create(en:"Cat Brier",scientific_name:"Smilax glabra",toxic:false)
Flower.create(en:"Cat Ear",scientific_name:"Calochortus spp.",toxic:false)
Flower.create(en:"Cattleya Labiata",scientific_name:"Cattleya labiata",toxic:false)
Flower.create(en:"Celosia Globosa",scientific_name:"Celosia globosa",toxic:false)
Flower.create(en:"Celosia Plumosa",scientific_name:"Celosia plumosa",toxic:false)
Flower.create(en:"Celosia Spicata",scientific_name:"Celosia spicata",toxic:false)
Flower.create(en:"Chamaedorea",scientific_name:"Chamaedorea elegans",toxic:false)
Flower.create(en:"Chaparral",scientific_name:"Larrea tridentata",toxic:false)
Flower.create(en:"Chenille Plant",scientific_name:"Acalypha hispida",toxic:false)
Flower.create(en:"Chervil",scientific_name:"Anthriscus cerefolium",toxic:false)
Flower.create(en:"Chestnut",scientific_name:"Castanea dentata",toxic:false)
Flower.create(en:"Chicken-Gizzard",scientific_name:"Iresine herbstii",toxic:false)
Flower.create(en:"Chickens and Hens",scientific_name:"Echeveria elegans",toxic:false)
Flower.create(en:"Chin-lao-shu",scientific_name:"Smilax glabra",toxic:false)
Flower.create(en:"China Aster",scientific_name:"Callistephus chinensis",toxic:false)
Flower.create(en:"China Root",scientific_name:"Smilax glabra",toxic:false)
Flower.create(en:"Chinese Plumbago",scientific_name:"Ceratostigma willmottianum",toxic:false)
Flower.create(en:"Chlorophytum",scientific_name:"Anthericum comosum",toxic:false)
Flower.create(en:"Chlorophytum bichetti",scientific_name:"Chlorophytum bichetti",toxic:false)
Flower.create(en:"Chocolate Soldier",scientific_name:"Episcia dianthiflora",toxic:false)
Flower.create(en:"Christmas Cactus",scientific_name:"Schlumbergera bridgesii",toxic:false)
Flower.create(en:"Christmas Dagger",scientific_name:"Polystichum acrostichoides",toxic:false)
Flower.create(en:"Christmas Orchid",scientific_name:"Cattleya trianaei",toxic:false)
Flower.create(en:"Christmas Palm",scientific_name:"Veitchia merrillii",toxic:false)
Flower.create(en:"Cilantro",scientific_name:"Coriandrum sativum",toxic:false)
Flower.create(en:"Cinnamon",scientific_name:"Cinnamomum zeylanicum",toxic:false)
Flower.create(en:"Cinquefoil",scientific_name:"Potentilla spp.",toxic:false)
Flower.create(en:"Cirrhopetalum",scientific_name:"Bulbophyllum appendiculatum",toxic:false)
Flower.create(en:"Clearweed",scientific_name:"Pilea pumila",toxic:false)
Flower.create(en:"Cliff Brake",scientific_name:"Pellaea rotundifolia",toxic:false)
Flower.create(en:"Club Moss",scientific_name:"Selaginella kraussiana",toxic:false)
Flower.create(en:"Cocks Comb",scientific_name:"Amaranthus hypochondriacus",toxic:false)
Flower.create(en:"Cocktail Orchid",scientific_name:"Cattleya forbesii",toxic:false)
Flower.create(en:"Collinia Elegans",scientific_name:"Chamaedorea elegans",toxic:false)
Flower.create(en:"Common Camellia",scientific_name:"Camellia japonica; Thea japonica",toxic:false)
Flower.create(en:"Common Catbrier",scientific_name:"Smilax rotundifolia",toxic:false)
Flower.create(en:"Common Garden Canna",scientific_name:"Canna generalis",toxic:false)
Flower.create(en:"Common Greenbrier",scientific_name:"Smilax rotundifolia",toxic:false)
Flower.create(en:"Common Snapdragon",scientific_name:"Antirrhinum majus",toxic:false)
Flower.create(en:"Common Staghorn Fern",scientific_name:"Platycerium bifurcatum",toxic:false)
Flower.create(en:"Confederate Jasmine",scientific_name:"Trachelospermum jasminoides",toxic:false)
Flower.create(en:"Coolwort",scientific_name:"Pilea pumila",toxic:false)
Flower.create(en:"Copper Rose",scientific_name:"Echeveria multicaulis",toxic:false)
Flower.create(en:"Copperleaf",scientific_name:"Acalypha godseffiana",toxic:false)
Flower.create(en:"Coral Bells",scientific_name:"Heuchera sanguinea",toxic:false)
Flower.create(en:"Coreopsis",scientific_name:"Coreopsis spp.",toxic:false)
Flower.create(en:"Cornflower",scientific_name:"Centaurea cyanus",toxic:false)
Flower.create(en:"Crape Myrtle",scientific_name:"Lagerstroemia indica",toxic:false)
Flower.create(en:"Creeping Charlie",scientific_name:"Pilea nummulariifolia",toxic:false)
Flower.create(en:"Creeping Gloxinia",scientific_name:"Asarina erubescens",toxic:false)
Flower.create(en:"Creeping Mahonia",scientific_name:"Mahonia aquifolium",toxic:false)
Flower.create(en:"Creeping Pilea",scientific_name:"Pilea nummulariifolia",toxic:false)
Flower.create(en:"Creeping Rubus",scientific_name:"Rubus pedatus",toxic:false)
Flower.create(en:"Creeping Zinnia",scientific_name:"Sanvitalia spp.",toxic:false)
Flower.create(en:"Crepe Myrtle",scientific_name:"Lagerstroemia indica",toxic:false)
Flower.create(en:"Crimson Bottlebush",scientific_name:"Callistemon species",toxic:false)
Flower.create(en:"Crimson Cup",scientific_name:"Neoregalia spp.",toxic:false)
Flower.create(en:"Crisped Feather Fern",scientific_name:"Nephrolepis biserrata",toxic:false)
Flower.create(en:"Crossandra",scientific_name:"Crossandra species",toxic:false)
Flower.create(en:"Cucumber",scientific_name:"Cucumis sativus",toxic:false)
Flower.create(en:"Cushion Aloe",scientific_name:"Aloe retusa",toxic:false)
Flower.create(en:"Cushion Moss",scientific_name:"Selaginella kraussiana",toxic:false)
Flower.create(en:"Cyrtudeira",scientific_name:"Episcia reptans",toxic:false)
Flower.create(en:"Dainty Rabbits-Foot Fern",scientific_name:"Davallia fejeensis",toxic:false)
Flower.create(en:"Dallas Fern",scientific_name:"Nephrolepis biserrata",toxic:false)
Flower.create(en:"Dancing Doll Orchid",scientific_name:"Oncidium flexuosum",toxic:false)
Flower.create(en:"Desert Trumpet",scientific_name:"Eriogonium inflatum",toxic:false)
Flower.create(en:"Dichelostemma",scientific_name:"Dichelostemma species",toxic:false)
Flower.create(en:"Dichorisandra Reginae",scientific_name:"Dichorisandra reginae",toxic:false)
Flower.create(en:"Dill",scientific_name:"Anethum graveolena",toxic:false)
Flower.create(en:"Dinteranthus",scientific_name:"Dinteranthus vanzylii",toxic:false)
Flower.create(en:"Duffii Fern",scientific_name:"Nephrolepsis cordifolia 'duffii'",toxic:false)
Flower.create(en:"Dwarf Date Palm",scientific_name:"Phoenix acaulis",toxic:false)
Flower.create(en:"Dwarf Feather Palm",scientific_name:"Nephrolepis exalta",toxic:false)
Flower.create(en:"Dwarf Palm",scientific_name:"Chamaedorea elegans",toxic:false)
Flower.create(en:"Dwarf Rose-Stripe Star",scientific_name:"Cryptanthus bivattus minor",toxic:false)
Flower.create(en:"Dwarf Royal Palm",scientific_name:"Veitchia merillii",toxic:false)
Flower.create(en:"Dwarf Whitman Fern",scientific_name:"Nephrolepsis cordifolia plumosa",toxic:false)
Flower.create(en:"Earth Star",scientific_name:"Cryptanthus bivattus minor",toxic:false)
Flower.create(en:"Easter Cattleya",scientific_name:"Cattleya mossiae",toxic:false)
Flower.create(en:"Easter Daisy",scientific_name:"Townsendia sericea",toxic:false)
Flower.create(en:"Easter Lily Cactus",scientific_name:"Echinopsis multiplex",toxic:false)
Flower.create(en:"Easter Orchid",scientific_name:"Cattleya mossiae",toxic:false)
Flower.create(en:"Edible Banana",scientific_name:"Musa acuminata",toxic:false)
Flower.create(en:"Emerald Ripple Peperomia",scientific_name:"Peperomia caperata",toxic:false)
Flower.create(en:"English Hawthorn",scientific_name:"Crataegus laevigata",toxic:false)
Flower.create(en:"Episcia",scientific_name:"Episcia dianthiflora",toxic:false)
Flower.create(en:"Fairy Fountain",scientific_name:"Celosia cristata",toxic:false)
Flower.create(en:"False Aralia",scientific_name:"Dizygotheca elegantissima",toxic:false)
Flower.create(en:"Fan Tufted Palm",scientific_name:"Rhapis flabelliformis",toxic:false)
Flower.create(en:"Feather Palm",scientific_name:"Nephrolepis exaltata",toxic:false)
Flower.create(en:"Fennel",scientific_name:"Foeniculum vulgare",toxic:false)
Flower.create(en:"Fiery Reed Orchid",scientific_name:"Epidendrum ibaguense",toxic:false)
Flower.create(en:"Fig Leaf Gourd",scientific_name:"Cucurbita ficifolia",toxic:false)
Flower.create(en:"Figleaf Palm",scientific_name:"Fatsia japonica",toxic:false)
Flower.create(en:"Fingernail Plant",scientific_name:"Neoregelia spectabilis",toxic:false)
Flower.create(en:"Fire Weed",scientific_name:"Epilobium angustifolium",toxic:false)
Flower.create(en:"Fish Tail Fern",scientific_name:"Cyrtomium falcatum",toxic:false)
Flower.create(en:"Flame African Violet",scientific_name:"Episcia reptans",toxic:false)
Flower.create(en:"Flame of the Woods",scientific_name:"Ixora coccinea",toxic:false)
Flower.create(en:"Florida Butterfly Orchid",scientific_name:"Epidendrum tampense",toxic:false)
Flower.create(en:"Florida Butterfly Orchid",scientific_name:"Encyclia tampensis",toxic:false)
Flower.create(en:"Fluffy Ruffles",scientific_name:"Nephrolepsis exalta",toxic:false)
Flower.create(en:"Forster Sentry Palm",scientific_name:"Howea forsteriana",toxic:false)
Flower.create(en:"Fortunes Palm",scientific_name:"Trachycarpus fortunei",toxic:false)
Flower.create(en:"Freckle Face",scientific_name:"Hypoestes phyllostachya",toxic:false)
Flower.create(en:"Friendship Plant",scientific_name:"Pilea involucrata",toxic:false)
Flower.create(en:"Garden Marigold",scientific_name:"Calendula officinalis",toxic:false)
Flower.create(en:"Garden Snapdragon",scientific_name:"Antirrhinum majus",toxic:false)
Flower.create(en:"Gerber Daisy",scientific_name:"Gerbera jamesonii",toxic:false)
Flower.create(en:"German Violet",scientific_name:"Exacum affine",toxic:false)
Flower.create(en:"Gherkins",scientific_name:"Cucumis sativus",toxic:false)
Flower.create(en:"Ghost Leafless Orchid",scientific_name:"Polyrrhiza lindenii",toxic:false)
Flower.create(en:"Ghost Plant",scientific_name:"Sedum weinbergii",toxic:false)
Flower.create(en:"Giant Aster",scientific_name:"Townsendia sericea",toxic:false)
Flower.create(en:"Giant Holly Fern",scientific_name:"Ploystichum munitum",toxic:false)
Flower.create(en:"Giant Touch-Me-Not",scientific_name:"Impatiens spp.",toxic:false)
Flower.create(en:"Giant White Inch Plant",scientific_name:"Albiflora spp.",toxic:false)
Flower.create(en:"Gibasis Geniculata",scientific_name:"Tradescantia multiflora",toxic:false)
Flower.create(en:"Globe Thistle",scientific_name:"Echinops spp.",toxic:false)
Flower.create(en:"Gloxinia",scientific_name:"Sinningia speciosa",toxic:false)
Flower.create(en:"Gold Bloom",scientific_name:"Calendula officinalis",toxic:false)
Flower.create(en:"Gold-Fish Plant",scientific_name:"Hypocyrta nummularia",toxic:false)
Flower.create(en:"Golden Bells",scientific_name:"Oleaceae",toxic:false)
Flower.create(en:"Golden Butterfly Palm",scientific_name:"Dypsis lutescens",toxic:false)
Flower.create(en:"Golden Lace Orchid",scientific_name:"Haemaria discolor",toxic:false)
Flower.create(en:"Golden Shower Orchid",scientific_name:"Oncidium sphacelatum",toxic:false)
Flower.create(en:"Good Luck Palm",scientific_name:"Chamaedorea elegans",toxic:false)
Flower.create(en:"Grape Hyacinth",scientific_name:"Muscari armeniacum",toxic:false)
Flower.create(en:"Grape Ivy",scientific_name:"Cissus rhombifolia",toxic:false)
Flower.create(en:"Great Willow Herb",scientific_name:"Epilobium angustifolium",toxic:false)
Flower.create(en:"Green Ripple Peperomia",scientific_name:"Peperomia caperata",toxic:false)
Flower.create(en:"Greenbrier",scientific_name:"Smilax glabra",toxic:false)
Flower.create(en:"Hagbrier",scientific_name:"Smilax hispida",toxic:false)
Flower.create(en:"Hardy Baby Tears",scientific_name:"Sedum album",toxic:false)
Flower.create(en:"Hardy Gloxinia",scientific_name:"Incarvillea delavayi",toxic:false)
Flower.create(en:"Hare Fern",scientific_name:"Davallia spp.",toxic:false)
Flower.create(en:"Haworthia",scientific_name:"Haworthia species",toxic:false)
Flower.create(en:"Haws",scientific_name:"Crataegus species",toxic:false)
Flower.create(en:"Haws Apple",scientific_name:"Crataegus species",toxic:false)
Flower.create(en:"Hawthorn",scientific_name:"Crataegus species",toxic:false)
Flower.create(en:"Hedgehog Gourd",scientific_name:"Cucumis dipsaceus",toxic:false)
Flower.create(en:"Hellfetter",scientific_name:"Smilax hispida",toxic:false)
Flower.create(en:"Hemlock Tree",scientific_name:"Tsuga species",toxic:false)
Flower.create(en:"Hen and Chickens Fern",scientific_name:"Asplenium bulbiferum",toxic:false)
Flower.create(en:"Hens and Chickens",scientific_name:"Echeveria elegans",toxic:false)
Flower.create(en:"Hibiscus",scientific_name:"Hibiscus syriacus",toxic:false)
Flower.create(en:"Hindu Rope Plant",scientific_name:"Hoya carnosa 'krinkle kurl'",toxic:false)
Flower.create(en:"Hoary Alyssum",scientific_name:"Berteroa incana",toxic:false)
Flower.create(en:"Holligold",scientific_name:"Calendula officinalis",toxic:false)
Flower.create(en:"Holly Fern",scientific_name:"Cyrtomium falcatum",toxic:false)
Flower.create(en:"Hollyhock",scientific_name:"Alcea rosea",toxic:false)
Flower.create(en:"Honey Locust",scientific_name:"Gleditsia triacanthos",toxic:false)
Flower.create(en:"Honey Plant",scientific_name:"Hoya carnosa",toxic:false)
Flower.create(en:"Honeydew Melon",scientific_name:"Cucumis melo",toxic:false)
Flower.create(en:"Honeysuckle Fuchsia",scientific_name:"Fuchsia triphylla",toxic:false)
Flower.create(en:"Hookera pulchella",scientific_name:"Dichelostemma pulchellum",toxic:false)
Flower.create(en:"Hubbard Squash",scientific_name:"Cucurbita maxima var. hubbard",toxic:false)
Flower.create(en:"Hypocyrta",scientific_name:"Hypocyrta nummularia",toxic:false)
Flower.create(en:"Ice Plant",scientific_name:"Lampranthus piquet",toxic:false)
Flower.create(en:"Impatience Plant",scientific_name:"Impatiens spp.",toxic:false)
Flower.create(en:"Irish Moss",scientific_name:"Selaginella kraussiana",toxic:false)
Flower.create(en:"Iron Tree",scientific_name:"Ixora coccinea",toxic:false)
Flower.create(en:"Ivy Peperomia",scientific_name:"Peperomia griseoargentea",toxic:false)
Flower.create(en:"Jackson Brier",scientific_name:"Smilax lanceolata",toxic:false)
Flower.create(en:"Jacob's Ladder",scientific_name:"Smilax herbacea",toxic:false)
Flower.create(en:"Japanese Aralia",scientific_name:"Fatsia japonica",toxic:false)
Flower.create(en:"Japanese Holly Fern",scientific_name:"Cyrtomium falcatum",toxic:false)
Flower.create(en:"Japanese Moss",scientific_name:"Selaginella kraussiana",toxic:false)
Flower.create(en:"Japanese Pittosporum",scientific_name:"Pittosporum tobira",toxic:false)
Flower.create(en:"Jasmine",scientific_name:"Jasminium species",toxic:false)
Flower.create(en:"Jewel Orchid",scientific_name:"Haemaria discolor",toxic:false)
Flower.create(en:"Joseph's Coat",scientific_name:"Iresine herbstii",toxic:false)
Flower.create(en:"Jungle Geranium",scientific_name:"Ixora javanica",toxic:false)
Flower.create(en:"Kaempferia",scientific_name:"Kaempferia spp.",toxic:false)
Flower.create(en:"Kahali Ginger",scientific_name:"Hedychium gardnerianum",toxic:false)
Flower.create(en:"Kenilworth Ivy",scientific_name:"Cymbalaria muralis",toxic:false)
Flower.create(en:"Kentia Palm",scientific_name:"Howea forsteriana",toxic:false)
Flower.create(en:"Kenya Violet",scientific_name:"Saintpaulia confusa",toxic:false)
Flower.create(en:"Kharoub",scientific_name:"Ceratonia siliqua",toxic:false)
Flower.create(en:"King and Queen Fern",scientific_name:"Asplenium bulbiferum",toxic:false)
Flower.create(en:"King Nut",scientific_name:"Carya laciniosa",toxic:false)
Flower.create(en:"King of the Forest",scientific_name:"Anoectuchilus setaceus",toxic:false)
Flower.create(en:"Kuang-yen-pa-hsieh",scientific_name:"Smilax glabra",toxic:false)
Flower.create(en:"Lace Fern",scientific_name:"Asparagus densiflorus cv sprengeri",toxic:false)
Flower.create(en:"Lace Flower Vine",scientific_name:"Episcia dianthiflora",toxic:false)
Flower.create(en:"Lace Orchid",scientific_name:"Odontoglossum crispum",toxic:false)
Flower.create(en:"Ladies Ear Drops",scientific_name:"Fuschsia spp.",toxic:false)
Flower.create(en:"Lady Lou",scientific_name:"Episcia reptans",toxic:false)
Flower.create(en:"Lady Palm",scientific_name:"Rhapis flabelliformus",toxic:false)
Flower.create(en:"Lady Slipper",scientific_name:"Impatiens spp.",toxic:false)
Flower.create(en:"Lagerstroemia Indica",scientific_name:"Lagerstroemia indica",toxic:false)
Flower.create(en:"Lance Pleomele",scientific_name:"Draceana spp.",toxic:false)
Flower.create(en:"Laurel-Leaved Greenbrier",scientific_name:"Smilax laurifolia",toxic:false)
Flower.create(en:"Leather Peperomia",scientific_name:"Peperomia crassifolia",toxic:false)
Flower.create(en:"Lemon Balm",scientific_name:"Melissa officinalis",toxic:false)
Flower.create(en:"Leopard Lily",scientific_name:"Lachenalia lilacina",toxic:false)
Flower.create(en:"Leopard Orchid",scientific_name:"Dendrobium gracilicaule",toxic:false)
Flower.create(en:"Lesser Snapdragon",scientific_name:"Antirrhinum orontium",toxic:false)
Flower.create(en:"Lily of the Valley Orchid",scientific_name:"Odontoglossum pulchellum",toxic:false)
Flower.create(en:"Linden",scientific_name:"Tilia americana",toxic:false)
Flower.create(en:"Lipstick Plant",scientific_name:"Aeschynanthus humilis",toxic:false)
Flower.create(en:"Little Fantasy Peperomia",scientific_name:"Peperomia caperata",toxic:false)
Flower.create(en:"Little Zebra Plant",scientific_name:"Haworthia subfasciata",toxic:false)
Flower.create(en:"Living Rock Cactus",scientific_name:"Pleiospilos bolusii",toxic:false)
Flower.create(en:"Living Stones",scientific_name:"Lithops naureeniae",toxic:false)
Flower.create(en:"Loco Weed",scientific_name:"Oxytropis spp.",toxic:false)
Flower.create(en:"Locust Pods",scientific_name:"Ceratonia siliqua",toxic:false)
Flower.create(en:"Madagascar Jasmine",scientific_name:"Stephanotis floribunda",toxic:false)
Flower.create(en:"Magnolia Bush",scientific_name:"Magnolia stellata",toxic:false)
Flower.create(en:"Mahonia",scientific_name:"Mahonia aquifolium",toxic:false)
Flower.create(en:"Majesty Palm",scientific_name:"Ravenea rivularis",toxic:false)
Flower.create(en:"Malabar Gourd",scientific_name:"Cucurbita ficifolia",toxic:false)
Flower.create(en:"Malaysian Dracaena",scientific_name:"Dracaena reflexa",toxic:false)
Flower.create(en:"Manila Palm",scientific_name:"Veitchia merrillii",toxic:false)
Flower.create(en:"Maranta",scientific_name:"Calathea insignis",toxic:false)
Flower.create(en:"Marbled Fingernail",scientific_name:"Neoregelia spectabilis",toxic:false)
Flower.create(en:"Mariposa Lily",scientific_name:"Calochortus gunnisonii",toxic:false)
Flower.create(en:"Maroon",scientific_name:"Echeveria multicaulis",toxic:false)
Flower.create(en:"Maroon Chenille Plant",scientific_name:"Echeveria derenbergii",toxic:false)
Flower.create(en:"Mary-Bud",scientific_name:"Calendula officinalis",toxic:false)
Flower.create(en:"Measles Plant",scientific_name:"Acantha",toxic:false)
Flower.create(en:"Metallic Peperomia",scientific_name:"Peperomia caperata",toxic:false)
Flower.create(en:"Mexican Firecracker",scientific_name:"Echeveria Pulinata",toxic:false)
Flower.create(en:"Mexican Rosettes",scientific_name:"Echevaria",toxic:false)
Flower.create(en:"Mexican Snowballs",scientific_name:"Echevaria",toxic:false)
Flower.create(en:"Miniature Date Palm",scientific_name:"Phoenix robellinii",toxic:false)
Flower.create(en:"Miniature Fish Tail",scientific_name:"Chamaedorea elegans",toxic:false)
Flower.create(en:"Miniature Maranta",scientific_name:"Calathea micans",toxic:false)
Flower.create(en:"Miniature Marble Plant",scientific_name:"Neoregelia spectabilis",toxic:false)
Flower.create(en:"Mistletoe Cactus",scientific_name:"Rhipsalis cassutha",toxic:false)
Flower.create(en:"Mockernut Hickory",scientific_name:"Carya tomentosa",toxic:false)
Flower.create(en:"Mosaic Plant",scientific_name:"Bertolonia mosaica",toxic:false)
Flower.create(en:"Mosaic Vase",scientific_name:"Guzmania musaica",toxic:false)
Flower.create(en:"Moss Agate",scientific_name:"Episcia reptans",toxic:false)
Flower.create(en:"Moss Campion",scientific_name:"Silene acaulis",toxic:false)
Flower.create(en:"Moss Fern",scientific_name:"Selaginella kraussiana",toxic:false)
Flower.create(en:"Moss Phlox",scientific_name:"Phlox subulata",toxic:false)
Flower.create(en:"Mossy Campion",scientific_name:"Silene acaulis",toxic:false)
Flower.create(en:"Mother Fern",scientific_name:"Asplenium bulbiferum",toxic:false)
Flower.create(en:"Mother of Pearl",scientific_name:"Secum weinbergii",toxic:false)
Flower.create(en:"Mother Spleenwort",scientific_name:"Asplenium bulbiferum",toxic:false)
Flower.create(en:"Mountain Camellia",scientific_name:"Stewartia ovata",toxic:false)
Flower.create(en:"Mountain Grape",scientific_name:"Mahonia aquifolium",toxic:false)
Flower.create(en:"Mulberry Bush Greenbrier",scientific_name:"Smilax sp.",toxic:false)
Flower.create(en:"Mulberry Tree",scientific_name:"Morus sp.",toxic:false)
Flower.create(en:"Musa Paradisiaca",scientific_name:"Musa acuminata",toxic:false)
Flower.create(en:"Muscari Armeniacum",scientific_name:"Muscari armeniacum",toxic:false)
Flower.create(en:"Muskmelon",scientific_name:"Cucumis melo",toxic:false)
Flower.create(en:"Nasturtium",scientific_name:"Tropaeolum majus",toxic:false)
Flower.create(en:"Natal Plum",scientific_name:"Carissa grandiflora",toxic:false)
Flower.create(en:"Neanthe Bella Palm",scientific_name:"Chamaedorea elegans",toxic:false)
Flower.create(en:"Nematanthus spp.",scientific_name:"Hypocyrta nummularia",toxic:false)
Flower.create(en:"Neoregelia",scientific_name:"Neoregalia spp.",toxic:false)
Flower.create(en:"Nerve Plant",scientific_name:"Fittonia verschaffeltii",toxic:false)
Flower.create(en:"Night Blooming Cereus",scientific_name:"Hylocereus undatus",toxic:false)
Flower.create(en:"Old Man Cactus",scientific_name:"Cephalocereus senilis",toxic:false)
Flower.create(en:"Old World Orchid",scientific_name:"Bulbophyllum appendiculatum",toxic:false)
Flower.create(en:"Orange Star",scientific_name:"Guzmania lingulata minor",toxic:false)
Flower.create(en:"Oregon Grape",scientific_name:"Mahonia aquifolium",toxic:false)
Flower.create(en:"Ossifragi Vase",scientific_name:"Neoregalia spp.",toxic:false)
Flower.create(en:"Paddys Wig",scientific_name:"Soleirolia soleirolii",toxic:false)
Flower.create(en:"Painted Lady",scientific_name:"Echeveria multicaulis",toxic:false)
Flower.create(en:"Pampas Grass",scientific_name:"Cortaderia selloana",toxic:false)
Flower.create(en:"Panamiga",scientific_name:"Pilea involucrata",toxic:false)
Flower.create(en:"Pansy Orchid",scientific_name:"Miltonia roezlii alba",toxic:false)
Flower.create(en:"Paradise Palm",scientific_name:"Howea forsteriana",toxic:false)
Flower.create(en:"Parlor Palm",scientific_name:"Chamaedorea elegans",toxic:false)
Flower.create(en:"Parsley Fern",scientific_name:"Asplenium bulbiferum",toxic:false)
Flower.create(en:"Patient Lucy",scientific_name:"Impatiens spp.",toxic:false)
Flower.create(en:"Patient Plant",scientific_name:"Impatiens spp.",toxic:false)
Flower.create(en:"Peacock Plant",scientific_name:"Kaempferia",toxic:false)
Flower.create(en:"Pearl Plant",scientific_name:"Haworthia margaritifera",toxic:false)
Flower.create(en:"Pearly Dots",scientific_name:"Haworthia margaritifera",toxic:false)
Flower.create(en:"Peperomia Hederifolia",scientific_name:"Peperomia griseoargentea",toxic:false)
Flower.create(en:"Peperomia Peltfolia",scientific_name:"Peperomia peltifolia",toxic:false)
Flower.create(en:"Peperomia Rotundifolia",scientific_name:"Peperomia rotundifolia",toxic:false)
Flower.create(en:"Peperomia Sandersii",scientific_name:"Peperomia sandersii",toxic:false)
Flower.create(en:"Pepper Face",scientific_name:"Peperomia obtusifolia",toxic:false)
Flower.create(en:"Persian Violet",scientific_name:"Exacum affine",toxic:false)
Flower.create(en:"Peruvian Lily",scientific_name:"Alstroemeria",toxic:false)
Flower.create(en:"Petunia",scientific_name:"Petunia species",toxic:false)
Flower.create(en:"Phalaenopsis Orchid",scientific_name:"Phalaenopsis sp.",toxic:false)
Flower.create(en:"Pheasant Plant",scientific_name:"Cryptanthus zonatus",toxic:false)
Flower.create(en:"Piggy Back Plant",scientific_name:"Tolmeia menziesii",toxic:false)
Flower.create(en:"Pignut Hickory",scientific_name:"Carya glabra",toxic:false)
Flower.create(en:"Pilea Microphylla",scientific_name:"Pilea microphylla",toxic:false)
Flower.create(en:"Pilea Mucosa",scientific_name:"Pilea microphylla",toxic:false)
Flower.create(en:"Pincushion Flower",scientific_name:"Leucospermum incisum",toxic:false)
Flower.create(en:"Pink Brocade",scientific_name:"Episcia cultivar",toxic:false)
Flower.create(en:"Pink Splash",scientific_name:"Hypoestes phyllostachya",toxic:false)
Flower.create(en:"Pink Starlite",scientific_name:"Cryptanthus bivattus minor",toxic:false)
Flower.create(en:"Pirliteiro",scientific_name:"Crataegus species",toxic:false)
Flower.create(en:"Pitaya",scientific_name:"Hylocereus undatus",toxic:false)
Flower.create(en:"Plantanus Occidentalis",scientific_name:"Plantanus occidentalis",toxic:false)
Flower.create(en:"Platinum Peperomia",scientific_name:"Peperomia griseoargentea",toxic:false)
Flower.create(en:"Platycerium Alcicorne",scientific_name:"Platycerium alcicorne",toxic:false)
Flower.create(en:"Plumbago Larpentiae",scientific_name:"Ceratostigma larpentiae",toxic:false)
Flower.create(en:"Plumosa Fern",scientific_name:"Asparagus densiflorus cv sprengeri",toxic:false)
Flower.create(en:"Plush Plant",scientific_name:"Echeveria pul-oliver",toxic:false)
Flower.create(en:"Poison Ivy",scientific_name:"Toxicodendron species",toxic:false)
Flower.create(en:"Poison Oak",scientific_name:"Toxicodendron species",toxic:false)
Flower.create(en:"Poison Sumac",scientific_name:"Toxicodendron species",toxic:false)
Flower.create(en:"Polka Dot Plant",scientific_name:"Hypoestes phyllostachya",toxic:false)
Flower.create(en:"Polystichum Falcatum",scientific_name:"Cyrtomium falcatum",toxic:false)
Flower.create(en:"Pony Tail",scientific_name:"Beaucarnea recurvata",toxic:false)
Flower.create(en:"Porcelain Flower",scientific_name:"Hoya carnosa 'krinkle kurl'",toxic:false)
Flower.create(en:"Pot Marigold",scientific_name:"Calendula officinalis",toxic:false)
Flower.create(en:"Prairie Lily",scientific_name:"Zephyranthes drummondii",toxic:false)
Flower.create(en:"Prayer Plant",scientific_name:"Calathea insignis",toxic:false)
Flower.create(en:"Prostrate Coleus",scientific_name:"Plectranthus oetendahlii",toxic:false)
Flower.create(en:"Pupleosier Willow",scientific_name:"Salix purpurea",toxic:false)
Flower.create(en:"Purple Baby Tears",scientific_name:"Frithia pulchra",toxic:false)
Flower.create(en:"Purple Passion Vine",scientific_name:"Gynura aurantica",toxic:false)
Flower.create(en:"Purple Velvet Plant",scientific_name:"Gynura aurantica",toxic:false)
Flower.create(en:"Purple Waffle Plant",scientific_name:"Hemigraphis exotica",toxic:false)
Flower.create(en:"Queencup",scientific_name:"Clintonia uniflora",toxic:false)
Flower.create(en:"Queens Spiderwort",scientific_name:"Dichorisandra reginae",toxic:false)
Flower.create(en:"Queensland Arrowroot",scientific_name:"Canna edulis",toxic:false)
Flower.create(en:"Rabbits Foot Fern",scientific_name:"Davallia spp.",toxic:false)
Flower.create(en:"Racemose asparagus",scientific_name:"Asparagus densiflorus cv sprengeri",toxic:false)
Flower.create(en:"Rainbow Orchid",scientific_name:"Epidendrum prismatocarpum",toxic:false)
Flower.create(en:"Red African Violet",scientific_name:"Episcia reptans",toxic:false)
Flower.create(en:"Red Berried Greenbrier",scientific_name:"Smilax walteria",toxic:false)
Flower.create(en:"Red Edge Peperomia",scientific_name:"Peperomia clusiifolia",toxic:false)
Flower.create(en:"Red Hawthorne",scientific_name:"Crataegus species",toxic:false)
Flower.create(en:"Red Maple",scientific_name:"Acer rubrum",toxic:false)
Flower.create(en:"Red Palm Lily",scientific_name:"Cordyline rubra",toxic:false)
Flower.create(en:"Red Veined Prayer",scientific_name:"Calathea insignis",toxic:false)
Flower.create(en:"Reed Palm",scientific_name:"Chamaedorea elegans",toxic:false)
Flower.create(en:"Resurrection Lily",scientific_name:"Kaempferia",toxic:false)
Flower.create(en:"Rhynchophorum",scientific_name:"Peperomia obtusifolia",toxic:false)
Flower.create(en:"Ribbon Plant",scientific_name:"Chlorophytum comosum",toxic:false)
Flower.create(en:"Roosevelt Fern",scientific_name:"Nephrolepis biserrata",toxic:false)
Flower.create(en:"Rose",scientific_name:"Rosa Species",toxic:false)
Flower.create(en:"Rose of China",scientific_name:"Hibiscus syriacus",toxic:false)
Flower.create(en:"Rose of Sharon",scientific_name:"Hibiscus syriacus",toxic:false)
Flower.create(en:"Rosemary",scientific_name:"Rosmarinus officinalis",toxic:false)
Flower.create(en:"Russian Knapweed",scientific_name:"Centaurea repens",toxic:false)
Flower.create(en:"Russian Olive",scientific_name:"elaeagnus species",toxic:false)
Flower.create(en:"Saffron Spike Zebra",scientific_name:"Aphelandra squarrosa",toxic:false)
Flower.create(en:"Sage",scientific_name:"Salvia officinalis",toxic:false)
Flower.create(en:"Saint Bernards Lily",scientific_name:"Anthericum liliago",toxic:false)
Flower.create(en:"Salad Burnet",scientific_name:"Poterium sanguisorba",toxic:false)
Flower.create(en:"Sand Lily",scientific_name:"Leucocrinum montanum",toxic:false)
Flower.create(en:"Sand Verbena",scientific_name:"Abronia fragrans",toxic:false)
Flower.create(en:"Satin Pellionia",scientific_name:"Pellonia pulchra",toxic:false)
Flower.create(en:"Savory",scientific_name:"Satureja hortensis",toxic:false)
Flower.create(en:"Savory",scientific_name:"Satureja hortensis",toxic:false)
Flower.create(en:"Sawbrier",scientific_name:"Smilax glauca",toxic:false)
Flower.create(en:"Scabious",scientific_name:"Leucospermum incisum",toxic:false)
Flower.create(en:"Scarborough Lily",scientific_name:"Vallota speciosa",toxic:false)
Flower.create(en:"Scarlet Orchid",scientific_name:"Epidendrum tampense",toxic:false)
Flower.create(en:"Scarlet Sage",scientific_name:"Salvia coccinea",toxic:false)
Flower.create(en:"Sego Lily",scientific_name:"Calochortus gunnisonii",toxic:false)
Flower.create(en:"Shagbark Hickory",scientific_name:"Carya laciniosa",toxic:false)
Flower.create(en:"Shan Ku'ei-lai",scientific_name:"Smilax glabra",toxic:false)
Flower.create(en:"Shellbark Hickory",scientific_name:"Carya laciniosa",toxic:false)
Flower.create(en:"Shrimp Cactus",scientific_name:"Schlumbergera russelliana",toxic:false)
Flower.create(en:"Silver Bell",scientific_name:"Halesia carolina",toxic:false)
Flower.create(en:"Silver Berry",scientific_name:"elaeagnus species",toxic:false)
Flower.create(en:"Silver Heart",scientific_name:"Peperomia caperata",toxic:false)
Flower.create(en:"Silver Pink Vine",scientific_name:"Hoya publcalyx",toxic:false)
Flower.create(en:"Silver Star",scientific_name:"Cryptanthus lacerdae",toxic:false)
Flower.create(en:"Silver Table Fern",scientific_name:"Pteris sp.",toxic:false)
Flower.create(en:"Silver Tree Anamiga",scientific_name:"NONE LISTED",toxic:false)
Flower.create(en:"Slender Deutzia",scientific_name:"Deutzia gracilis",toxic:false)
Flower.create(en:"Small Fruited Hickory",scientific_name:"Carya glabra",toxic:false)
Flower.create(en:"Smilax Tamnoides Vas",scientific_name:"Smilax hispida",toxic:false)
Flower.create(en:"Speckled Wood Lily",scientific_name:"Clintonia umbelluata",toxic:false)
Flower.create(en:"Spice Orchid",scientific_name:"Epidendrum atropurpeum",toxic:false)
Flower.create(en:"Spice Orchid",scientific_name:"Epidendrum ibaguense",toxic:false)
Flower.create(en:"Spider Flower",scientific_name:"Cleome hasserlana",toxic:false)
Flower.create(en:"Spider Ivy",scientific_name:"Chlorophytum comosum",toxic:false)
Flower.create(en:"Spider Plant",scientific_name:"Chlorophytum comosum",toxic:false)
Flower.create(en:"Sprengeri Fern",scientific_name:"Asparagus densiflorus cv sprengeri",toxic:false)
Flower.create(en:"Star Jasmine",scientific_name:"Trachelospermum jasminoides",toxic:false)
Flower.create(en:"Star Lily",scientific_name:"Leucocrinum montanum",toxic:false)
Flower.create(en:"Star Plant",scientific_name:"Cryptanthus bivattus minor",toxic:false)
Flower.create(en:"Stevia",scientific_name:"Stevia rebaudiana",toxic:false)
Flower.create(en:"Strawberry",scientific_name:"Fragaria spp.",toxic:false)
Flower.create(en:"Striped Blushing",scientific_name:"Neoregalia spp.",toxic:false)
Flower.create(en:"Sudan Grass",scientific_name:"Sorghum vulgare var sudanesis",toxic:false)
Flower.create(en:"Sugar Pods",scientific_name:"Ceratonia siliqua",toxic:false)
Flower.create(en:"Sulfur Flower",scientific_name:"Eriogonium umbellatum",toxic:false)
Flower.create(en:"Summer Hyacinth",scientific_name:"Galtonia spp.",toxic:false)
Flower.create(en:"Sunflower",scientific_name:"helianthus angustifolius",toxic:false)
Flower.create(en:"Swamp Sunflower",scientific_name:"helianthus angustifolius",toxic:false)
Flower.create(en:"Swedish Ivy",scientific_name:"Plectranthus australis",toxic:false)
Flower.create(en:"Sweet Potato Vine",scientific_name:"Ipomoea batatas",toxic:false)
Flower.create(en:"Sweetheart Hoya",scientific_name:"Hoya kerrii",toxic:false)
Flower.create(en:"Sword Fern",scientific_name:"Nephrolepis biserrata",toxic:false)
Flower.create(en:"Tailed Orchid",scientific_name:"Masdevallia spp.",toxic:false)
Flower.create(en:"Tall Feather Fern",scientific_name:"Nephrolepis biserrata",toxic:false)
Flower.create(en:"Tall Mahonia",scientific_name:"Mahonia aquifolium",toxic:false)
Flower.create(en:"Tangerine Impatience",scientific_name:"Impatiens spp.",toxic:false)
Flower.create(en:"Teasel Gourd",scientific_name:"Cucumis dipsaceus",toxic:false)
Flower.create(en:"Texas Sage",scientific_name:"Salvia coccinea",toxic:false)
Flower.create(en:"Thea Japonica",scientific_name:"Camellia japonica",toxic:false)
Flower.create(en:"Thimble Cactus",scientific_name:"Mammillaria fragilis",toxic:false)
Flower.create(en:"Thorn Apple",scientific_name:"Crataegus douglasii",toxic:false)
Flower.create(en:"Thyme",scientific_name:"Thymus vulgaris",toxic:false)
Flower.create(en:"Ti hu-ling",scientific_name:"Smilax glabra",toxic:false)
Flower.create(en:"Tickseed",scientific_name:"Coreopsis californica",toxic:false)
Flower.create(en:"Tiger Orchid",scientific_name:"Haemaria discolor",toxic:false)
Flower.create(en:"Toad Spotted Cactus",scientific_name:"Stapelia variegata",toxic:false)
Flower.create(en:"Torch Lily",scientific_name:"Kniphofia",toxic:false)
Flower.create(en:"Tous-les-mois",scientific_name:"Canna edulis",toxic:false)
Flower.create(en:"Trailing Peperomia",scientific_name:"Peperomia prostata",toxic:false)
Flower.create(en:"Tree Cactus",scientific_name:"Opuntia species",toxic:false)
Flower.create(en:"Tree Gloxinia",scientific_name:"Kohleria lindeniana",toxic:false)
Flower.create(en:"Tropical Moss",scientific_name:"Selaginella kraussiana",toxic:false)
Flower.create(en:"True Cantaloupe",scientific_name:"Cucumis melo",toxic:false)
Flower.create(en:"Tu Fu-Ling",scientific_name:"Smilax glabra",toxic:false)
Flower.create(en:"Tulip Poplar",scientific_name:"Liriodendron tulipifera",toxic:false)
Flower.create(en:"Turban Squash",scientific_name:"Cucurbita maxima cv turbaniformis",toxic:false)
Flower.create(en:"Turf Lily",scientific_name:"Liriope muscari",toxic:false)
Flower.create(en:"Umbrella Plant",scientific_name:"Eriogonium umbellatum",toxic:false)
Flower.create(en:"Urbinia Agavoides",scientific_name:"Echeveria elegans",toxic:false)
Flower.create(en:"Usambara Violet",scientific_name:"Santpaulia confusa",toxic:false)
Flower.create(en:"Variegated Laurel",scientific_name:"Tradescantia flumeninsis",toxic:false)
Flower.create(en:"Variegated Wax Plant",scientific_name:"Echeveria sp.",toxic:false)
Flower.create(en:"Velvet Plant",scientific_name:"Gynura aurantica",toxic:false)
Flower.create(en:"Venus Fly Trap",scientific_name:"Dionaea muscipula",toxic:false)
Flower.create(en:"Verona Fern",scientific_name:"Nephrolepis biserrata",toxic:false)
Flower.create(en:"Verona Lace Fern",scientific_name:"Nephrolepis biserrata",toxic:false)
Flower.create(en:"Vining Peperomia",scientific_name:"Peperomia serpens variegata",toxic:false)
Flower.create(en:"Violet Slipper Gloxinia",scientific_name:"Sinningia speciosa",toxic:false)
Flower.create(en:"Waffle Plant",scientific_name:"Hemigraphis exotica",toxic:false)
Flower.create(en:"Walking Anthericum",scientific_name:"Chlorophytum comosum",toxic:false)
Flower.create(en:"Washington Hawthorn",scientific_name:"Crataegus species",toxic:false)
Flower.create(en:"Water Hickory",scientific_name:"Carya aquatica",toxic:false)
Flower.create(en:"Water Hyacinth",scientific_name:"Eichhornia crassipes",toxic:false)
Flower.create(en:"Watermelon Begonia",scientific_name:"Peperomia argyreia",toxic:false)
Flower.create(en:"Watermelon Peperomia",scientific_name:"Peperomia argyreia",toxic:false)
Flower.create(en:"Watermelon Pilea",scientific_name:"Pilea cadieri",toxic:false)
Flower.create(en:"Wax Plant",scientific_name:"Hoya carnosa 'krinkle kurl'",toxic:false)
Flower.create(en:"Wax Rosette",scientific_name:"Echeveria gilva",toxic:false)
Flower.create(en:"Weeping Bottlebrush",scientific_name:"Callistemon species",toxic:false)
Flower.create(en:"Weeping Sargent Hemlock",scientific_name:"Tsuga species",toxic:false)
Flower.create(en:"Weisdornbluten",scientific_name:"Crataegus species",toxic:false)
Flower.create(en:"West Indian Gherkin",scientific_name:"Cucumis anguria",toxic:false)
Flower.create(en:"Western Sword",scientific_name:"Ploystichum munitum",toxic:false)
Flower.create(en:"White Edged Swedish Ivy",scientific_name:"Plectranthus australis",toxic:false)
Flower.create(en:"White Ginger",scientific_name:"Hedychium coronarium",toxic:false)
Flower.create(en:"White Heart Hickory",scientific_name:"Carya tomentosa",toxic:false)
Flower.create(en:"Whitman Fern",scientific_name:"Nephrolepis biserrata",toxic:false)
Flower.create(en:"Wild Buckwheat",scientific_name:"Eriogonium umbellatum",toxic:false)
Flower.create(en:"Wild Hyacinth",scientific_name:"Dichelostemma pulchellum",toxic:false)
Flower.create(en:"Wild Lantana",scientific_name:"Abronia fragrans",toxic:false)
Flower.create(en:"Wild Sasparilla",scientific_name:"Smilax glauca",toxic:false)
Flower.create(en:"Wild Strawberry",scientific_name:"Fragaria",toxic:false)
Flower.create(en:"Willow Herb",scientific_name:"Epilobium angustifolium",toxic:false)
Flower.create(en:"Windmill Palm",scientific_name:"Trachycarpus fortunei",toxic:false)
Flower.create(en:"Winter Cattleya",scientific_name:"Cattleya trianaei",toxic:false)
Flower.create(en:"Withered Snapdragon",scientific_name:"Anthirrhinum multiflorum",toxic:false)
Flower.create(en:"Woolflower",scientific_name:"Celosia cristata",toxic:false)
Flower.create(en:"Yellow Bloodleaf",scientific_name:"Iresine herbstii",toxic:false)
Flower.create(en:"Yellow Palm",scientific_name:"Dypsis lutescens",toxic:false)
Flower.create(en:"Yellow-Flowered Gourd",scientific_name:"Cucurbita species",toxic:false)
Flower.create(en:"Yellowrocket",scientific_name:"Barbarea vulgaris",toxic:false)
Flower.create(en:"Yorba Linda",scientific_name:"Peperomia rotundifolia",toxic:false)
Flower.create(en:"Zebra Haworthia",scientific_name:"Haworthia fasciata",toxic:false)
Flower.create(en:"Zinnia",scientific_name:"Zinnia species",toxic:false)
Flower.create(en:"Zucchini Squash",scientific_name:"Cucurbia pepo cv zucchini",toxic:false)
Flower.create(en:"Adam-and-Eve",scientific_name:"Arum maculatum",toxic:true)
Flower.create(en:"African Wonder Tree",scientific_name:"Ricinus communis",toxic:true)
Flower.create(en:"Alocasia",scientific_name:"Alocasia spp.",toxic:true)
Flower.create(en:"Aloe",scientific_name:"Aloe vera",toxic:true)
Flower.create(en:"Amaryllis",scientific_name:"Amaryllis spp.",toxic:true)
Flower.create(en:"Ambrosia Mexicana",scientific_name:"Chenopodium botrys",toxic:true)
Flower.create(en:"American Bittersweet",scientific_name:"Celastrus scandens",toxic:true)
Flower.create(en:"American Holly",scientific_name:"Ilex opaca",toxic:true)
Flower.create(en:"American Mandrake",scientific_name:"Podophyllum peltatum",toxic:true)
Flower.create(en:"American Yew",scientific_name:"Taxus canadensus",toxic:true)
Flower.create(en:"Andromeda Japonica",scientific_name:"Pieris japonica",toxic:true)
Flower.create(en:"Angelica Tree",scientific_name:"Aralia spinosa",toxic:true)
Flower.create(en:"Apple",scientific_name:"Malus sylvestrus",toxic:true)
Flower.create(en:"Apricot",scientific_name:"Prunus armeniaca",toxic:true)
Flower.create(en:"Arrow-Head Vine",scientific_name:"Syngonium podophyllum",toxic:true)
Flower.create(en:"Arum",scientific_name:"Arum maculatum",toxic:true)
Flower.create(en:"Arum Lily",scientific_name:"Zantedeschia aethiopica",toxic:true)
Flower.create(en:"Asian Lily",scientific_name:"Lilium asiatica",toxic:true)
Flower.create(en:"Australian Ivy Palm",scientific_name:"Brassaia actinophylla",toxic:true)
Flower.create(en:"Autumn Crocus",scientific_name:"Colchicum autumnale",toxic:true)
Flower.create(en:"Azalea",scientific_name:"Rhododendron spp",toxic:true)
Flower.create(en:"Baby Doll Ti Plant",scientific_name:"Cordyline terminalis",toxic:true)
Flower.create(en:"Barbados Aloe",scientific_name:"Aloe barbadensis",toxic:true)
Flower.create(en:"Barbados Lily",scientific_name:"Hippeastrum spp.",toxic:true)
Flower.create(en:"Barbados Pride",scientific_name:"Caesalpinia pulcherrima",toxic:true)
Flower.create(en:"Barbados Pride 2",scientific_name:"Poinciana gilliesii",toxic:true)
Flower.create(en:"Bay Laurel",scientific_name:"Laurus nobilis",toxic:true)
Flower.create(en:"Bead Tree",scientific_name:"Melia azedarach",toxic:true)
Flower.create(en:"Begonia",scientific_name:"Begonia spp.",toxic:true)
Flower.create(en:"Bergamot Orange",scientific_name:"Citrus Aurantium",toxic:true)
Flower.create(en:"Bird of Paradise",scientific_name:"Caesalpinia gilliesii",toxic:true)
Flower.create(en:"Bird of Paradise 2",scientific_name:"Poinciana gilliesii",toxic:true)
Flower.create(en:"Bird of Paradise Flower",scientific_name:"Strelitzia reginae",toxic:true)
Flower.create(en:"Bird's Tongue Flower",scientific_name:"Strelitzia reginae",toxic:true)
Flower.create(en:"Bishop’s Weed",scientific_name:"Ammi majus",toxic:true)
Flower.create(en:"Bitter Root",scientific_name:"Apocynum androsaemifolium",toxic:true)
Flower.create(en:"Black Calla",scientific_name:"Arum palestinum",toxic:true)
Flower.create(en:"Black Cherry",scientific_name:"Prunus serotina",toxic:true)
Flower.create(en:"Black Laurel",scientific_name:"Leucothoe spp.",toxic:true)
Flower.create(en:"Black Nightshade",scientific_name:"Solanum nigrum",toxic:true)
Flower.create(en:"Bobbins",scientific_name:"Arum maculatum",toxic:true)
Flower.create(en:"Bog Laurel",scientific_name:"Kalmia poliifolia",toxic:true)
Flower.create(en:"Borage",scientific_name:"Borage officinalis",toxic:true)
Flower.create(en:"Boxwood",scientific_name:"Buxus spp.",toxic:true)
Flower.create(en:"Branching Ivy",scientific_name:"Hedera helix",toxic:true)
Flower.create(en:"Brazilwood",scientific_name:"Poinciana gilliesii",toxic:true)
Flower.create(en:"Bread and Butter Plant",scientific_name:"Coleus ampoinicus",toxic:true)
Flower.create(en:"Brunfelsia",scientific_name:"Brunfelsia species",toxic:true)
Flower.create(en:"Buckeye",scientific_name:"Aesculus spp",toxic:true)
Flower.create(en:"Buckwheat",scientific_name:"Fagopyrum spp.",toxic:true)
Flower.create(en:"Buddhist Pine",scientific_name:"Podocarpus macrophylla",toxic:true)
Flower.create(en:"Burning Bush",scientific_name:"Euonymus atropurpurea",toxic:true)
Flower.create(en:"Buttercup",scientific_name:"Ranunculus spp.",toxic:true)
Flower.create(en:"Butterfly Iris",scientific_name:"Iris spuria",toxic:true)
Flower.create(en:"Caladium",scientific_name:"Caladium hortulanum",toxic:true)
Flower.create(en:"Calamondin Orange",scientific_name:"Citrus mitis",toxic:true)
Flower.create(en:"California Ivy",scientific_name:"Hedera helix",toxic:true)
Flower.create(en:"Calla Lily",scientific_name:"Zantedeschia aethiopica",toxic:true)
Flower.create(en:"Cape Jasmine",scientific_name:"Gardenia jasminoides",toxic:true)
Flower.create(en:"Caraway",scientific_name:"Carum carvi",toxic:true)
Flower.create(en:"Cardboard Cycad",scientific_name:"Zamia furfuracea",toxic:true)
Flower.create(en:"Cardboard Palm",scientific_name:"Zamia spp.",toxic:true)
Flower.create(en:"Cardinal Flower",scientific_name:"Lobelia cardinalis",toxic:true)
Flower.create(en:"Carnation",scientific_name:"Dianthus caryophyllus",toxic:true)
Flower.create(en:"Castor Bean Plant",scientific_name:"Ricinus communis",toxic:true)
Flower.create(en:"Catnip",scientific_name:"Nepeta cataria",toxic:true)
Flower.create(en:"Ceriman",scientific_name:"Monstera deliciosa",toxic:true)
Flower.create(en:"Chamomile",scientific_name:"Anthemis nobilis",toxic:true)
Flower.create(en:"Chandelier Plant",scientific_name:"Kalanchoe tubiflora",toxic:true)
Flower.create(en:"Charming Dieffenbachia",scientific_name:"Dieffenbachia amoena",toxic:true)
Flower.create(en:"Cherry",scientific_name:"Prunus spp.",toxic:true)
Flower.create(en:"Chinaberry Tree",scientific_name:"Melia azedarach",toxic:true)
Flower.create(en:"Chinese Evergreen",scientific_name:"Aglaonema modestum",toxic:true)
Flower.create(en:"Chinese Jade",scientific_name:"Crassula arborescens",toxic:true)
Flower.create(en:"Chives",scientific_name:"Allium schoenoprasum",toxic:true)
Flower.create(en:"Choke Cherry",scientific_name:"Prunus virginiana",toxic:true)
Flower.create(en:"Christmas Rose",scientific_name:"Helleborus niger",toxic:true)
Flower.create(en:"Chrysanthemum",scientific_name:"Chrysanthemum spp.",toxic:true)
Flower.create(en:"Clematis",scientific_name:"Clematis spp.",toxic:true)
Flower.create(en:"Climbing Bittersweet",scientific_name:"Celastrus scandens",toxic:true)
Flower.create(en:"Climbing Lily",scientific_name:"Gloriosa superba",toxic:true)
Flower.create(en:"Climbing Nightshade",scientific_name:"Solanum dulcamara",toxic:true)
Flower.create(en:"Clivia Lily",scientific_name:"Clivia spp.",toxic:true)
Flower.create(en:"Coffee Tree",scientific_name:"Polyscias guilfoylei",toxic:true)
Flower.create(en:"Coleus",scientific_name:"Coleus ampoinicus",toxic:true)
Flower.create(en:"Common Privet",scientific_name:"Ligustrum vulgare",toxic:true)
Flower.create(en:"Coontie Palm",scientific_name:"Zamia pumila",toxic:true)
Flower.create(en:"Cordatum",scientific_name:"Philodendron oxycardium",toxic:true)
Flower.create(en:"Corn Plant",scientific_name:"Dracaena fragrans",toxic:true)
Flower.create(en:"Cornstalk Plant",scientific_name:"Dracaena fragrans",toxic:true)
Flower.create(en:"Cow parsnip",scientific_name:"Heracleum maximum",toxic:true)
Flower.create(en:"Cowbane",scientific_name:"Cicuta species",toxic:true)
Flower.create(en:"Cuckoo-pint",scientific_name:"Arum maculatum",toxic:true)
Flower.create(en:"Cutleaf Philodendron",scientific_name:"Monstera deliciosa",toxic:true)
Flower.create(en:"Cycads",scientific_name:"Cycas and Zamia species",toxic:true)
Flower.create(en:"Cyclamen",scientific_name:"Cyclamen spp",toxic:true)
Flower.create(en:"Daffodil",scientific_name:"Narcissus spp",toxic:true)
Flower.create(en:"Dahlia",scientific_name:"Dahlia species",toxic:true)
Flower.create(en:"Daisy",scientific_name:"Chrysanthemum species",toxic:true)
Flower.create(en:"Day Lilies",scientific_name:"Hemerocallis spp.",toxic:true)
Flower.create(en:"Deadly Nightshade",scientific_name:"Solanum spp",toxic:true)
Flower.create(en:"Desert Azalea",scientific_name:"Adenium obesum",toxic:true)
Flower.create(en:"Desert Rose",scientific_name:"Adenium obesum",toxic:true)
Flower.create(en:"Devil's Backbone",scientific_name:"Kalanchoe tubiflora",toxic:true)
Flower.create(en:"Devils Ivy",scientific_name:"Epipremnum aureum",toxic:true)
Flower.create(en:"Dieffenbachia",scientific_name:"Dieffenbachia",toxic:true)
Flower.create(en:"Dock",scientific_name:"Rumex sp.",toxic:true)
Flower.create(en:"Dog Daisy",scientific_name:"Achillea millefolium",toxic:true)
Flower.create(en:"Dog Hobble",scientific_name:"Leucothoe sp.",toxic:true)
Flower.create(en:"Dogbane Hemp",scientific_name:"Apocynum spp.",toxic:true)
Flower.create(en:"Dracaena",scientific_name:"Dracaena spp.",toxic:true)
Flower.create(en:"Dumbcane",scientific_name:"Dieffenbachia",toxic:true)
Flower.create(en:"Dwarf Poinciana",scientific_name:"Caesalpinia pulcherrima",toxic:true)
Flower.create(en:"Easter Lily",scientific_name:"Lilium longiflorum",toxic:true)
Flower.create(en:"Easter Rose",scientific_name:"Helleborus niger",toxic:true)
Flower.create(en:"Eastern Star",scientific_name:"Dianthus spp.",toxic:true)
Flower.create(en:"Elephant Ears",scientific_name:"Caladium hortulanum",toxic:true)
Flower.create(en:"Elephant Ears",scientific_name:"Colocasia esculenta",toxic:true)
Flower.create(en:"Elephant-Ear Begonia",scientific_name:"Begonia scharfii",toxic:true)
Flower.create(en:"Emerald Feather",scientific_name:"Asparagus densiflorus",toxic:true)
Flower.create(en:"English Holly",scientific_name:"Ilex aquifolium",toxic:true)
Flower.create(en:"English Ivy",scientific_name:"Hedera helix",toxic:true)
Flower.create(en:"English Yew",scientific_name:"Taxus baccata",toxic:true)
Flower.create(en:"Epazote",scientific_name:"Chenopodium ambrosioides",toxic:true)
Flower.create(en:"Eucalyptus",scientific_name:"Eucalyptus species",toxic:true)
Flower.create(en:"European Bittersweet",scientific_name:"Solanum dulcamara",toxic:true)
Flower.create(en:"European Holly",scientific_name:"Ilex aquifolium",toxic:true)
Flower.create(en:"Everlasting Pea",scientific_name:"Lathyrus latifolius",toxic:true)
Flower.create(en:"Exotica",scientific_name:"Dieffenbachia amoena",toxic:true)
Flower.create(en:"False Bittersweet",scientific_name:"Celastrus scandens",toxic:true)
Flower.create(en:"False Queen Anne’s Lace",scientific_name:"Ammi majus",toxic:true)
Flower.create(en:"Feather Geranium",scientific_name:"Ambrosia mexicana",toxic:true)
Flower.create(en:"Fern Palm",scientific_name:"Zamia spp.",toxic:true)
Flower.create(en:"Fetter Bush",scientific_name:"Leucothoe spp.",toxic:true)
Flower.create(en:"Fetterbush",scientific_name:"Lyonia spp.",toxic:true)
Flower.create(en:"Fiddle-Leaf",scientific_name:"Philodendron bipennifolium",toxic:true)
Flower.create(en:"Fig",scientific_name:"Ficus benjamina",toxic:true)
Flower.create(en:"Figwort",scientific_name:"Ranunculus acris",toxic:true)
Flower.create(en:"Fire Lily",scientific_name:"Hippeastrum spp.",toxic:true)
Flower.create(en:"Flag",scientific_name:"Iris species",toxic:true)
Flower.create(en:"Flamingo Flower",scientific_name:"Anthurium scherzeranum",toxic:true)
Flower.create(en:"Fleabane",scientific_name:"Erigeron speciosus",toxic:true)
Flower.create(en:"Florida Beauty",scientific_name:"Dracaena surculosa",toxic:true)
Flower.create(en:"Florist's Calla",scientific_name:"Zantedeschia aethiopica",toxic:true)
Flower.create(en:"Foxglove",scientific_name:"Digitalis purpurea",toxic:true)
Flower.create(en:"Franciscan Rain Tree",scientific_name:"Brunfelsia species",toxic:true)
Flower.create(en:"Garden Calla",scientific_name:"Zantedeschia aethiopica",toxic:true)
Flower.create(en:"Garden Chamomile",scientific_name:"Anthemis nobilis",toxic:true)
Flower.create(en:"Garden Hyacinth",scientific_name:"Hyacinthus orientalis",toxic:true)
Flower.create(en:"Gardenia",scientific_name:"Gardenia jasminoides",toxic:true)
Flower.create(en:"Garlic",scientific_name:"Allium sativum",toxic:true)
Flower.create(en:"Geranium",scientific_name:"Pelargonium species",toxic:true)
Flower.create(en:"Geranium-Leaf Aralia",scientific_name:"Polyscias guilfoylei",toxic:true)
Flower.create(en:"Giant Dracaena",scientific_name:"Cordyline australis",toxic:true)
Flower.create(en:"Giant Dumb Cane",scientific_name:"Dieffenbachia amoena",toxic:true)
Flower.create(en:"Giant Hogweed",scientific_name:"Heracleum maximum",toxic:true)
Flower.create(en:"Glacier Ivy",scientific_name:"Hedera helix",toxic:true)
Flower.create(en:"Gladiola",scientific_name:"Gladiolus species",toxic:true)
Flower.create(en:"Gloriosa Lily",scientific_name:"Gloriosa superba",toxic:true)
Flower.create(en:"Gold Dieffenbachia",scientific_name:"Dieffenbachia picta",toxic:true)
Flower.create(en:"Gold Dust Dracaena",scientific_name:"Dracaena surculosa",toxic:true)
Flower.create(en:"Golden Birds Nest",scientific_name:"Sansevieria trifasciata",toxic:true)
Flower.create(en:"Golden Pothos",scientific_name:"Epipremnum aureum",toxic:true)
Flower.create(en:"Golden Ragwort",scientific_name:"Senecio species",toxic:true)
Flower.create(en:"Good Luck Plant",scientific_name:"Oxalis spp.",toxic:true)
Flower.create(en:"Grapefruit",scientific_name:"Citrus paradisii",toxic:true)
Flower.create(en:"Grass Palm",scientific_name:"Cordyline australis",toxic:true)
Flower.create(en:"Greater Ammi",scientific_name:"Ammi majus",toxic:true)
Flower.create(en:"Green Gold Naphthysis",scientific_name:"Syngonium podophyllum",toxic:true)
Flower.create(en:"Ground Apple",scientific_name:"Anthemis nobilis",toxic:true)
Flower.create(en:"Groundsel",scientific_name:"Senecio species",toxic:true)
Flower.create(en:"Hahn's Self Branching English Ivy",scientific_name:"Hedera helix",toxic:true)
Flower.create(en:"Hashish",scientific_name:"Cannabis sativa",toxic:true)
Flower.create(en:"Hawaiian Ti",scientific_name:"Giant Dracaena",toxic:true)
Flower.create(en:"Heartleaf Philodendron",scientific_name:"Philodendron bipennifolium",toxic:true)
Flower.create(en:"Heavenly Bamboo",scientific_name:"Nandina domestica",toxic:true)
Flower.create(en:"Hellebore",scientific_name:"Helleborus niger",toxic:true)
Flower.create(en:"Hercules' Club",scientific_name:"Aralia spinosa",toxic:true)
Flower.create(en:"Hills of Snow",scientific_name:"Hydrangea arborescens",toxic:true)
Flower.create(en:"Holly",scientific_name:"Ilex opaca",toxic:true)
Flower.create(en:"Horse Chestnut",scientific_name:"Aesculus glabra",toxic:true)
Flower.create(en:"Horsehead Philodendron",scientific_name:"Philodendron bipennifolium",toxic:true)
Flower.create(en:"Horseweed",scientific_name:"Erigeron speciosus",toxic:true)
Flower.create(en:"Hortensia",scientific_name:"Hydrangea arborescens",toxic:true)
Flower.create(en:"Hosta",scientific_name:"Hosta plataginea",toxic:true)
Flower.create(en:"Hurricane Plant",scientific_name:"Monstera deliciosa",toxic:true)
Flower.create(en:"Hyacinth",scientific_name:"Hyacinthus orientalis",toxic:true)
Flower.create(en:"Hydrangea",scientific_name:"Hydrangea arborescens",toxic:true)
Flower.create(en:"Impala Lily",scientific_name:"Adenium obesum",toxic:true)
Flower.create(en:"Indian Apple",scientific_name:"Podophyllum peltatum",toxic:true)
Flower.create(en:"Indian Borage",scientific_name:"Coleus ampoinicus",toxic:true)
Flower.create(en:"Indian Hemp",scientific_name:"Apocynum androsaemifolium",toxic:true)
Flower.create(en:"Indian Hemp",scientific_name:"Cannabis sativa",toxic:true)
Flower.create(en:"Indian Pink",scientific_name:"Lobelia cardinalis",toxic:true)
Flower.create(en:"Indian Rubber Plant",scientific_name:"Ficus benjamina",toxic:true)
Flower.create(en:"Inkberry",scientific_name:"Ilex opaca",toxic:true)
Flower.create(en:"Iris",scientific_name:"Iris species",toxic:true)
Flower.create(en:"Iron Cross Begonia",scientific_name:"Begonia masoniana",toxic:true)
Flower.create(en:"Ivy Arum",scientific_name:"Epipremnum aureum",toxic:true)
Flower.create(en:"Jack-in-the-pulpit",scientific_name:"Arisaema triphyllum",toxic:true)
Flower.create(en:"Jade Plant",scientific_name:"Crassula argentea",toxic:true)
Flower.create(en:"Japanese Show Lily",scientific_name:"Lilium speciosum",toxic:true)
Flower.create(en:"Japanese Yew",scientific_name:"Taxus sp.",toxic:true)
Flower.create(en:"Jerusalem Cherry",scientific_name:"Solanum pseudocapsicum",toxic:true)
Flower.create(en:"Jerusalem Oak",scientific_name:"Ambrosia mexicana",toxic:true)
Flower.create(en:"Jonquil",scientific_name:"Narcissus jonquilla",toxic:true)
Flower.create(en:"Kaffir Lily",scientific_name:"Clivia minata",toxic:true)
Flower.create(en:"Kalanchoe",scientific_name:"Kalanchoe spp",toxic:true)
Flower.create(en:"Kiss-me-quick",scientific_name:"Brunfelsia species",toxic:true)
Flower.create(en:"Klamath Weed",scientific_name:"Hypericum perforatum",toxic:true)
Flower.create(en:"Kudu Lily",scientific_name:"Adenium obesum",toxic:true)
Flower.create(en:"Lacy Tree Philodendron",scientific_name:"Philodendron selloum",toxic:true)
Flower.create(en:"Lady-of-the-night",scientific_name:"Brunfelsia species",toxic:true)
Flower.create(en:"Lambkill",scientific_name:"Kalmia augustifolia",toxic:true)
Flower.create(en:"Lantana",scientific_name:"Lantana camara",toxic:true)
Flower.create(en:"Larkspur",scientific_name:"Delphinium species",toxic:true)
Flower.create(en:"Laurel",scientific_name:"Kalmia latifolia",toxic:true)
Flower.create(en:"Lavender",scientific_name:"Lavendula angustifolia",toxic:true)
Flower.create(en:"Leatherflower",scientific_name:"Clematis sp.",toxic:true)
Flower.create(en:"Leek",scientific_name:"Allium ampeloprasum",toxic:true)
Flower.create(en:"Lemon",scientific_name:"Citrus limonia",toxic:true)
Flower.create(en:"Lemon Grass",scientific_name:"Cymbopogon citratus",toxic:true)
Flower.create(en:"Lemon Verbena",scientific_name:"Aloysia triphylla",toxic:true)
Flower.create(en:"Lenten Rose",scientific_name:"Helleborus niger",toxic:true)
Flower.create(en:"Lily",scientific_name:"Lilium species",toxic:true)
Flower.create(en:"Lily of the Palace",scientific_name:"Hippeastrum spp.",toxic:true)
Flower.create(en:"Lily of the Valley",scientific_name:"Convallaria majalis",toxic:true)
Flower.create(en:"Lily-of-the-Valley Bush",scientific_name:"Pieris japonica",toxic:true)
Flower.create(en:"Lime",scientific_name:"Citrus aurantifolia",toxic:true)
Flower.create(en:"Lobelia",scientific_name:"Lobelia cardinalis",toxic:true)
Flower.create(en:"Locust",scientific_name:"Robinia spp.",toxic:true)
Flower.create(en:"Lord-and-Ladies",scientific_name:"Arum maculatum",toxic:true)
Flower.create(en:"Lovage",scientific_name:"Levisticum officinale",toxic:true)
Flower.create(en:"Madagascar Dragon Tree",scientific_name:"Dracaena marginata",toxic:true)
Flower.create(en:"Maidens Breath",scientific_name:"Gypsophila elegans",toxic:true)
Flower.create(en:"Malanga",scientific_name:"Colocasia esculenta",toxic:true)
Flower.create(en:"Maleberry",scientific_name:"Lyonia sp.",toxic:true)
Flower.create(en:"Mapleleaf Begonia",scientific_name:"Begonia cleopatra",toxic:true)
Flower.create(en:"Marble Queen",scientific_name:"Scindapsus aureus",toxic:true)
Flower.create(en:"Marijuana",scientific_name:"Cannabis sativa",toxic:true)
Flower.create(en:"Marjoram",scientific_name:"Origanum majorana",toxic:true)
Flower.create(en:"Mauna Loa Peace Lily",scientific_name:"Spathiphyllum",toxic:true)
Flower.create(en:"Mayapple",scientific_name:"Podophyllum peltatum",toxic:true)
Flower.create(en:"Mayweed",scientific_name:"Anthemis cotula",toxic:true)
Flower.create(en:"Meadow Saffron",scientific_name:"Colchicum autumnale",toxic:true)
Flower.create(en:"Medicine Plant",scientific_name:"",toxic:true)
Flower.create(en:"Metallic Leaf Begonia",scientific_name:"Begonia metallica",toxic:true)
Flower.create(en:"Mexican Breadfruit",scientific_name:"Monstera deliciosa",toxic:true)
Flower.create(en:"Milfoil",scientific_name:"Achillea millefolium",toxic:true)
Flower.create(en:"Milkweed",scientific_name:"Asclepias species",toxic:true)
Flower.create(en:"Mint",scientific_name:"Mentha sp.",toxic:true)
Flower.create(en:"Mistletoe American",scientific_name:"Phoradendron flavescens",toxic:true)
Flower.create(en:"Mock Azalea",scientific_name:"Adenium obesum",toxic:true)
Flower.create(en:"Mole Bean Plant",scientific_name:"Ricinus communis",toxic:true)
Flower.create(en:"Morning Glory",scientific_name:"Ipomoea spp",toxic:true)
Flower.create(en:"Morning-Noon-and-Night",scientific_name:"Brunfelsia species",toxic:true)
Flower.create(en:"Moss Rose",scientific_name:"Portulaca oleracea",toxic:true)
Flower.create(en:"Mother of Millions",scientific_name:"Kalanchoe tubiflora",toxic:true)
Flower.create(en:"Mother-in-Law",scientific_name:"Monstera deliciosa",toxic:true)
Flower.create(en:"Mother-In-Law Plant",scientific_name:"Kalanchoe tubiflora",toxic:true)
Flower.create(en:"Mother-in-Law’s Tongue",scientific_name:"Sansevieria trifasciata",toxic:true)
Flower.create(en:"Mum",scientific_name:"Chrysanthemum spp.",toxic:true)
Flower.create(en:"Naked Lady",scientific_name:"Amaryllis spp.",toxic:true)
Flower.create(en:"Nandina",scientific_name:"Nandina domestica",toxic:true)
Flower.create(en:"Narcissus",scientific_name:"Narcissus spp",toxic:true)
Flower.create(en:"Nasturtium",scientific_name:"Nasturtium officinale",toxic:true)
Flower.create(en:"Needlepoint Ivy",scientific_name:"Hedera helix",toxic:true)
Flower.create(en:"Nephthytis",scientific_name:"Syngonium podophyllum",toxic:true)
Flower.create(en:"Nicotiana",scientific_name:"Nicotiana glauca",toxic:true)
Flower.create(en:"Nightshade",scientific_name:"Solanum spp",toxic:true)
Flower.create(en:"Octopus Tree",scientific_name:"Schefflera or Brassia actinoplylla",toxic:true)
Flower.create(en:"Oilcloth Flower",scientific_name:"Anthurium scherzeranum",toxic:true)
Flower.create(en:"Oleander",scientific_name:"Nerium oleander",toxic:true)
Flower.create(en:"Onion",scientific_name:"Allium cepa",toxic:true)
Flower.create(en:"Orange",scientific_name:"Citrus sinensis",toxic:true)
Flower.create(en:"Orange Day Lily",scientific_name:"Hemerocallis graminea",toxic:true)
Flower.create(en:"Oregano",scientific_name:"Origanum vulgare hirtum",toxic:true)
Flower.create(en:"Oregon Holly",scientific_name:"Ilex opaca",toxic:true)
Flower.create(en:"Ornamental Pepper",scientific_name:"Solanum pseudocapsicum",toxic:true)
Flower.create(en:"Pacific Yew",scientific_name:"Taxus brevifolia",toxic:true)
Flower.create(en:"Painter's Pallette",scientific_name:"Anthurium scherzeranum",toxic:true)
Flower.create(en:"Palm Lily",scientific_name:"Cordyline australis",toxic:true)
Flower.create(en:"Panda Plant",scientific_name:"Philodendron bipennifolium",toxic:true)
Flower.create(en:"Paper White",scientific_name:"Narcissus spp",toxic:true)
Flower.create(en:"Paraguayan Jasmine",scientific_name:"Brunfelsia species",toxic:true)
Flower.create(en:"Parsley",scientific_name:"Petroselinum crispum",toxic:true)
Flower.create(en:"Peace Begonia",scientific_name:"Begonia rex 'peace'",toxic:true)
Flower.create(en:"Peace Lily",scientific_name:"Spathiphyllum",toxic:true)
Flower.create(en:"Peach",scientific_name:"Prunus persica",toxic:true)
Flower.create(en:"Peacock Flower",scientific_name:"Caesalpinia pulcherrima",toxic:true)
Flower.create(en:"Pencil Cactus",scientific_name:"Euphorbia tirucalli",toxic:true)
Flower.create(en:"Peony",scientific_name:"Paeonis officinalis",toxic:true)
Flower.create(en:"Perennial Pea",scientific_name:"Lathyrus latifolius",toxic:true)
Flower.create(en:"Periwinkle",scientific_name:"Vinca rosea",toxic:true)
Flower.create(en:"Philodendron Pertusum",scientific_name:"Philodendron spp",toxic:true)
Flower.create(en:"Pie Plant",scientific_name:"Rheum rhabarbarium",toxic:true)
Flower.create(en:"Pieris",scientific_name:"Pieris japonica",toxic:true)
Flower.create(en:"Pig Lily",scientific_name:"Zantedeschia aethiopica",toxic:true)
Flower.create(en:"Pigtail Plant",scientific_name:"Anthurium scherzeranum",toxic:true)
Flower.create(en:"Pink Pearl",scientific_name:"Begonia semperflorens cultivar",toxic:true)
Flower.create(en:"Pinks",scientific_name:"Dianthus caryophyllus",toxic:true)
Flower.create(en:"Plantain Lily",scientific_name:"Hosta plantaginea",toxic:true)
Flower.create(en:"Plum",scientific_name:"Prunus domestica",toxic:true)
Flower.create(en:"Poinciana",scientific_name:"Caesalpinia gilliessi",toxic:true)
Flower.create(en:"Poinsettia",scientific_name:"Euphorbia pulcherrima",toxic:true)
Flower.create(en:"Poison Daisy",scientific_name:"Anthemis cotula",toxic:true)
Flower.create(en:"Poison Hemlock",scientific_name:"Conium maculatum",toxic:true)
Flower.create(en:"Poison Parsnip",scientific_name:"Cicuta maculata",toxic:true)
Flower.create(en:"Portulaca",scientific_name:"Portulaca oleracea",toxic:true)
Flower.create(en:"Prayer Bean",scientific_name:"Abrus precatorius",toxic:true)
Flower.create(en:"Pride-of-India",scientific_name:"Melia azedarach",toxic:true)
Flower.create(en:"Primrose",scientific_name:"Primula vulgaris",toxic:true)
Flower.create(en:"Privet",scientific_name:"Ligustrum japonicum",toxic:true)
Flower.create(en:"Purslane",scientific_name:"Portulaca oleracea",toxic:true)
Flower.create(en:"Ragwort",scientific_name:"Senecio species",toxic:true)
Flower.create(en:"Ranger's Button",scientific_name:"Sphenosciadium capitellatum",toxic:true)
Flower.create(en:"Red Emerald",scientific_name:"Philodendron bipennifolium",toxic:true)
Flower.create(en:"Red Lily",scientific_name:"Lilium umbellatum",toxic:true)
Flower.create(en:"Red Princess",scientific_name:"Philodendron bipennifolium",toxic:true)
Flower.create(en:"Red-Marginated Dracaena",scientific_name:"Dracaena marginata",toxic:true)
Flower.create(en:"Rex Begonia",scientific_name:"Begonia rex",toxic:true)
Flower.create(en:"Rhododendron",scientific_name:"Rhododendron spp",toxic:true)
Flower.create(en:"Rhubarb",scientific_name:"Rheum rhabarbarium",toxic:true)
Flower.create(en:"Ribbon Plant",scientific_name:"Dracaena spp.",toxic:true)
Flower.create(en:"Ridderstjerne",scientific_name:"Hippeastrum spp.",toxic:true)
Flower.create(en:"Rock Moss",scientific_name:"Portulaca oleracea",toxic:true)
Flower.create(en:"Roman Chamomile",scientific_name:"Anthemis nobilis",toxic:true)
Flower.create(en:"Rosebay",scientific_name:"Rhododendron spp",toxic:true)
Flower.create(en:"Rubrum Lily",scientific_name:"Lilium speciosum",toxic:true)
Flower.create(en:"Running Myrtle",scientific_name:"Vinca rosea",toxic:true)
Flower.create(en:"Sabi Star",scientific_name:"Adenium obesum",toxic:true)
Flower.create(en:"Sacred Bamboo",scientific_name:"Nandina domestica",toxic:true)
Flower.create(en:"Saddle Leaf",scientific_name:"Philodendron bipennifolium",toxic:true)
Flower.create(en:"Sago Palm",scientific_name:"Cycas revoluta, zamia species",toxic:true)
Flower.create(en:"Satin Pothos",scientific_name:"Scindapsus pictus",toxic:true)
Flower.create(en:"Scented Geranium",scientific_name:"Pelargonium sp.",toxic:true)
Flower.create(en:"Schefflera",scientific_name:"Schefflera",toxic:true)
Flower.create(en:"Seaside Daisy",scientific_name:"Erigeron speciosus",toxic:true)
Flower.create(en:"Seven Bark",scientific_name:"Hydrangea arborescens",toxic:true)
Flower.create(en:"Shamrock Plant",scientific_name:"Oxalis spp.",toxic:true)
Flower.create(en:"Shatavari",scientific_name:"Asparagus densiflorus cv sprengeri",toxic:true)
Flower.create(en:"Showy Daisy",scientific_name:"Erigeron speciosus",toxic:true)
Flower.create(en:"Silver Dollar",scientific_name:"Crassula arborescens",toxic:true)
Flower.create(en:"Silver Jade Plant",scientific_name:"Crassula arborescens",toxic:true)
Flower.create(en:"Skunk Cabbage",scientific_name:"Symplocarpus foetidus",toxic:true)
Flower.create(en:"Snake Lilly",scientific_name:"Iris species",toxic:true)
Flower.create(en:"Snake Plant",scientific_name:"Sansevieria trifasciata",toxic:true)
Flower.create(en:"Solomon’s Lily",scientific_name:"Arum palestinum",toxic:true)
Flower.create(en:"Sorrel",scientific_name:"Rumex scutatus",toxic:true)
Flower.create(en:"Sowbread",scientific_name:"Cyclamen spp",toxic:true)
Flower.create(en:"Spanish Thyme",scientific_name:"Coleus ampoinicus",toxic:true)
Flower.create(en:"Spindle Tree",scientific_name:"Euonymus atropurpurea",toxic:true)
Flower.create(en:"Split Leaf Philodendron",scientific_name:"Philodendron bipennifolium",toxic:true)
Flower.create(en:"Spotted Dumb Cane",scientific_name:"Dieffenbachia amoena",toxic:true)
Flower.create(en:"Spring Parsley",scientific_name:"Cymopterus watsonii",toxic:true)
Flower.create(en:"St. John’s Wort",scientific_name:"Hypericum perforatum",toxic:true)
Flower.create(en:"Staggerbush",scientific_name:"Lyonia sp.",toxic:true)
Flower.create(en:"Starch Root",scientific_name:"Arum maculatum",toxic:true)
Flower.create(en:"Stargazer Lily",scientific_name:"Lilium orientalis",toxic:true)
Flower.create(en:"Starleaf",scientific_name:"Brassaia actinophylla",toxic:true)
Flower.create(en:"Stinking Chamomile",scientific_name:"Anthemis cotula",toxic:true)
Flower.create(en:"Straight-Margined Dracaena",scientific_name:"Dracaena marginata",toxic:true)
Flower.create(en:"Striped Dracaena",scientific_name:"Dracaena deremensis",toxic:true)
Flower.create(en:"Superb Lily",scientific_name:"Gloriosa superba",toxic:true)
Flower.create(en:"Sweet Cherry",scientific_name:"Prunus avium",toxic:true)
Flower.create(en:"Sweet Pea",scientific_name:"Lathyrus latifolius",toxic:true)
Flower.create(en:"Sweet William",scientific_name:"Dianthus caryophyllus",toxic:true)
Flower.create(en:"Sweetheart Ivy",scientific_name:"Hedera helix",toxic:true)
Flower.create(en:"Swiss Cheese Plant",scientific_name:"Monstera deliciosa",toxic:true)
Flower.create(en:"Tahitian Bridal Veil",scientific_name:"tradescantia multiflora",toxic:true)
Flower.create(en:"Tail Flower",scientific_name:"Anthurium scherzeranum",toxic:true)
Flower.create(en:"Taro",scientific_name:"Caladium hortulanum",toxic:true)
Flower.create(en:"Taro",scientific_name:"Colocasia esculenta",toxic:true)
Flower.create(en:"Taro Vine",scientific_name:"Epipremnum aureum",toxic:true)
Flower.create(en:"Tarragon",scientific_name:"Artemisia dracunculus",toxic:true)
Flower.create(en:"Texas Umbrella Tree",scientific_name:"Melia azedarach",toxic:true)
Flower.create(en:"Ti-Plant",scientific_name:"Cordyline terminalis",toxic:true)
Flower.create(en:"Tiger Lily",scientific_name:"Lilium tigrinum",toxic:true)
Flower.create(en:"Tobacco",scientific_name:"Nicotiana glauca",toxic:true)
Flower.create(en:"Tomato Plant",scientific_name:"Lycopersicon spp",toxic:true)
Flower.create(en:"Tree Philodendron",scientific_name:"Philodendron selloum",toxic:true)
Flower.create(en:"Tree Tobacco",scientific_name:"Nicotiana glauca",toxic:true)
Flower.create(en:"Tropic Snow",scientific_name:"Dieffenbachia amoena",toxic:true)
Flower.create(en:"True Aloe",scientific_name:"Aloe barbadensis",toxic:true)
Flower.create(en:"Trumpet Lily",scientific_name:"Zantedeschia aethiopica",toxic:true)
Flower.create(en:"Tulip",scientific_name:"Tulipa spp.",toxic:true)
Flower.create(en:"Umbrella Leaf",scientific_name:"Podophyllum peltatum",toxic:true)
Flower.create(en:"Umbrella Tree",scientific_name:"Brassaia actinophylla",toxic:true)
Flower.create(en:"Variable Dieffenbachia",scientific_name:"Dieffenbachia picta",toxic:true)
Flower.create(en:"Variegated Philodendron",scientific_name:"Scindapsus, Philodendron spp",toxic:true)
Flower.create(en:"Variegated Wandering Jew",scientific_name:"Tradescantia flumeninsis",toxic:true)
Flower.create(en:"Vinca",scientific_name:"Vinca rosea",toxic:true)
Flower.create(en:"Virgin's Bower",scientific_name:"Clematis sp.",toxic:true)
Flower.create(en:"Wahoo",scientific_name:"Euonymus occidentalis",toxic:true)
Flower.create(en:"Wake Robin",scientific_name:"Arum maculatum",toxic:true)
Flower.create(en:"Wandering Jew",scientific_name:"Tradescantia flumeninsis",toxic:true)
Flower.create(en:"Warneckei Dracaena",scientific_name:"Dracaena deremensis",toxic:true)
Flower.create(en:"Water Flag",scientific_name:"Iris species",toxic:true)
Flower.create(en:"Water Hemlock",scientific_name:"Cicuta maculata",toxic:true)
Flower.create(en:"Wax-Leaf",scientific_name:"Ligustrum japonicum",toxic:true)
Flower.create(en:"Weeping Fig",scientific_name:"Ficus sp.",toxic:true)
Flower.create(en:"Western Yew",scientific_name:"Taxus brevifolia",toxic:true)
Flower.create(en:"White Heads",scientific_name:"Sphenosciadium capitellatum",toxic:true)
Flower.create(en:"Wild Arum",scientific_name:"Arum palestinum",toxic:true)
Flower.create(en:"Wild Calla",scientific_name:"Arum palestinum",toxic:true)
Flower.create(en:"Wild Carnation",scientific_name:"Dianthus caryophyllus",toxic:true)
Flower.create(en:"Wild Coffee",scientific_name:"Polyscias guilfoylei",toxic:true)
Flower.create(en:"Winter Cherry",scientific_name:"Solanum pseudocapsicum",toxic:true)
Flower.create(en:"Winterberry",scientific_name:"Ilex opaca",toxic:true)
Flower.create(en:"Wisteria",scientific_name:"Wisteria spp.",toxic:true)
Flower.create(en:"Wood Lily",scientific_name:"Lilium umbellatum",toxic:true)
Flower.create(en:"Yarrow",scientific_name:"Achillea millefolium",toxic:true)
Flower.create(en:"Yellow Oleander",scientific_name:"Thevetia peruviana",toxic:true)
Flower.create(en:"Yesterday, Today, Tomorrow",scientific_name:"Brunfelsia species",toxic:true)
Flower.create(en:"Yew",scientific_name:"Taxus spp.",toxic:true)
Flower.create(en:"Yew Pine",scientific_name:"Podocarpus macrophylla",toxic:true)
Flower.create(en:"Yucca",scientific_name:"Yucca spp.",toxic:true)



